#!/usr/bin/env node
const fs=require('fs'),path=require('path');
function args(argv){const o={};for(let i=2;i<argv.length;i++){if(!argv[i].startsWith('--'))continue;const k=argv[i].slice(2);o[k]=argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:true;}return o;}
const a=args(process.argv),project=path.resolve(a.project||process.cwd()),appRoot=path.resolve(project,a['app-root']||'src/app'),routeRoot=path.resolve(project,a['route-root']||'src/app'),output=path.resolve(project,a.output||'pageRegistry.generated.json'),tsOutput=a['ts-output']?path.resolve(project,a['ts-output']):null;
function walk(d){return fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>{const f=path.join(d,e.name);return e.isDirectory()?walk(f):[f]});}
function human(v){return v.replace(/\.(web|ios|android)$/,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function route(file){const r=path.relative(appRoot,file).replace(/\\/g,'/');return'/'+r.replace(/\.tsx?$/,'').replace(/\/index$/,'').replace(/\/(\([^/]+\))(?=\/|$)/g,'');}
function candidates(b){return[b,`${b}.tsx`,`${b}.ts`,`${b}.jsx`,`${b}.js`,path.join(b,'index.tsx'),path.join(b,'index.ts')];}
function resolveImport(s,from){let b=null;if(s.startsWith('@/'))b=path.join(project,'src',s.slice(2));else if(s.startsWith('./')||s.startsWith('../'))b=path.resolve(path.dirname(from),s);if(!b)return null;return candidates(b).find(f=>fs.existsSync(f)&&fs.statSync(f).isFile())||null;}
function linked(entry,max=2){const seen=new Set(),chunks=[];function visit(file,depth){if(!file||seen.has(file)||depth>max||seen.size>30)return;seen.add(file);const src=fs.readFileSync(file,'utf8');chunks.push(src);for(const m of src.matchAll(/(?:from\s*|import\s*\()\s*["']([^"']+)["']/g)){const f=resolveImport(m[1],file);if(f&&(f.includes(`${path.sep}src${path.sep}aix${path.sep}`)||depth===0))visit(f,depth+1);}}visit(entry,0);return chunks.join('\n');}
function params(src){const n=new Set();for(const m of src.matchAll(/useLocalSearchParams\s*<([\s\S]*?)>\s*\(/g))for(const p of m[1].matchAll(/([A-Za-z_$][\w$]*)\??\s*:/g))n.add(p[1]);for(const m of src.matchAll(/(?:params|routeParams)\.([A-Za-z_$][\w$]*)/g))n.add(m[1]);for(const m of src.matchAll(/(?:const|let)\s*{([^}]+)}\s*=\s*useLocalSearchParams/g))for(const item of m[1].split(',')){const x=item.trim().split(/[:=]/)[0].trim();if(/^[A-Za-z_$][\w$]*$/.test(x))n.add(x);}return[...n].sort();}
function caps(src){const c=[['camera',/expo-camera|CameraView/],['biometric',/NativeBiometric|biometric/i],['webview',/react-native-webview|AixWebview/],['file-picker',/image-picker|document-picker/],['share',/react-native-share|expo-sharing/],['screenshot',/react-native-view-shot/]];return c.filter(([,r])=>r.test(src)).map(([n])=>n);}
function presets(file){if(!file)return{routePresets:{},nonVisualRoutes:[]};const x=require(path.resolve(project,file));return{routePresets:x.routePresets||x.default||{},nonVisualRoutes:x.nonVisualRoutes||[]};}
const ignored=new Set(['_layout.tsx','_layout.ts','[...slug].tsx','RouterOptions.tsx','page-gallery.tsx']),segments=String(a.ignore||'playground').split(',').map(x=>x.trim()).filter(Boolean),files=walk(routeRoot).filter(f=>/\.tsx?$/.test(f)&&!ignored.has(path.basename(f))&&!segments.some(s=>path.relative(routeRoot,f).replace(/\\/g,'/').split('/').includes(s))),loaded=presets(a.presets),nonVisual=new Set(loaded.nonVisualRoutes),internal=new Set(String(a.internal||'debug,route').split(',').filter(Boolean));
const rows=files.map(file=>{const r=route(file),src=linked(file),s=r.replace(/^\//,'').split('/').filter(Boolean),category=s[1]||s[0]||'root';return{id:r.replace(/^\//,'').replace(/[^a-zA-Z0-9]+/g,'-'),title:human(s.at(-1)||'App'),category,route:r,sourcePath:path.relative(project,file).replace(/\\/g,'/'),params:params(src),previewParams:loaded.routePresets[r]||{},nativeCapabilities:caps(src),internal:internal.has(category),nonVisual:nonVisual.has(r)}}).sort((x,y)=>x.category.localeCompare(y.category)||x.route.localeCompare(y.route));
fs.mkdirSync(path.dirname(output),{recursive:true});fs.writeFileSync(output,JSON.stringify(rows,null,2)+'\n');if(tsOutput){fs.mkdirSync(path.dirname(tsOutput),{recursive:true});const t='export type PageRegistryEntry = { id: string; title: string; category: string; route: string; sourcePath: string; params: string[]; previewParams: Record<string,string>; nativeCapabilities: string[]; internal: boolean; nonVisual: boolean; };\n\n';fs.writeFileSync(tsOutput,`${t}export const pageRegistry: PageRegistryEntry[] = ${JSON.stringify(rows,null,2)};\n`);}console.log(JSON.stringify({routes:rows.length,output,tsOutput},null,2));
